---
devices:
  samplerate: 48000
  enable_rate_adjust: true
  chunksize: 2048
  silence_threshold: -60
  silence_timeout: 3.0
  capture:
    type: Alsa
    channels: 2
    device: "hw:Loopback,1,0"
    format: S32LE
  playback:
    type: Alsa
    channels: 2
    device: "dmix:UCM"
    format: S16LE

mixers:
  stereoToLeft:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: 0
            inverted: false

filters:
  lowpass:
    description: Nuttall FIR lowpass
    type: Conv
    parameters:
      type: Raw
      filename: /home/amp/RPi-multiroom-audio/CamillaDSP/Configuration/Coefficients/nuttall-o4095-c2500-s48000-w1.txt
      format: TEXT
  highpass:
    description: Nuttall FIR highpass
    type: Conv
    parameters:
      type: Raw
      filename: /home/amp/RPi-multiroom-audio/CamillaDSP/Configuration/Coefficients/nuttall-o4095-c2500-s48000-w2.txt
      format: TEXT

pipeline:
  - type: Mixer
    name: stereoToLeft
  - type: Filter
    channels:
      - 0
    names:
      - lowpass
  - type: Filter
    channels:
      - 1
    names:
      - highpass


