---
devices:
  samplerate: 48000
  chunksize: 2048
  silence_threshold: -60
  silence_timeout: 3.0
  capture:
    type: Alsa
    channels: 2
    device: "hw:Loopback,1,0"
    format: S32LE
  playback:
    type: Alsa
    channels: 2
    device: "dmix:sndrpijustboomd"
    format: S32LE

mixers:
  monoToStereo:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: -40
            inverted: false
          - channel: 1
            gain: -40
            inverted: false

pipeline:
  - type: Mixer
    name: monoToStereo
