# Loopback device
pcm.bluetooth_to_loopback {
    type plug
    slave {
        pcm {
            type rate
            slave {
                pcm "dmix:Loopback,0,1"
                rate 48000
            }
            converter "speexrate_medium"
        }
        format S32_LE
    }
}

pcm.dmixer_loopback {
    type dmix
    ipc_key 1024
    ipc_perm 0666
    slave {
        pcm "hw:Loopback,0,1"
        rate 48000
        #period_size 4096
        #buffer_size 32768
        period_size 16384
        buffer_size 65536
    }
}
