---
camilla_host: "127.0.0.1"
camilla_port: 5005
bind_address: "AudioAmp.local"
port: 5005
ssl_certificate: null
ssl_private_key: null
config_dir: "/home/amp/Documents/RPi-multiroom-audio/CamillaDSP/Configuration/Configurations"
coeff_dir: "/home/amp/Documents/RPi-multiroom-audio/CamillaDSP/Configuration/Coefficients"
default_config: "/home/amp/Documents/RPi-multiroom-audio/CamillaDSP/Configuration/Coefficients/default.yaml"
statefile_path: "/home/amp/Documents/RPi-multiroom-audio/CamillaDSP/Backend/statefile.yml"
log_file: "/home/amp/Documents/RPi-multiroom-audio/CamillaDSP/Backend/camilladsp.log"
on_set_active_config: null
on_get_active_config: null
supported_capture_types: null
supported_playback_types: null
