title: Bessel IIR crossover
description: 'This crossover is for a 2-way loudspeaker with a transition from bass to treble at 3.5 kHz.

It is built on IIR Bessel filters which has a maximally flat group delay in the passband.
Both filters are of 8th order and are made with the series connection of 4 biquads.
'
devices:
  samplerate: 192000
  capture_samplerate: 192000
  resampler: null
  enable_rate_adjust: false
  chunksize: 2048
  capture:
    channels: 2
    device: hw:Loopback,1,0
    format: S32LE
    type: Alsa
  playback:
    channels: 2
    device: dmix:sndrpihifiberry
    format: S32LE
    type: Alsa
  silence_threshold: -60
  silence_timeout: 3
  queuelimit: null
  rate_measure_interval: null
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: null
  adjust_period: null

filters:
  lowpass1:
    description: null
    parameters:
      freq: 3830.27
      q: 1.22567
      type: Lowpass
    type: Biquad
  lowpass2:
    description: null
    parameters:
      freq: 3418.09
      q: 0.710852
      type: Lowpass
    type: Biquad
  lowpass3:
    description: null
    parameters:
      freq: 3206.16
      q: 0.559609
      type: Lowpass
    type: Biquad
  lowpass4:
    description: null
    parameters:
      freq: 3112.32
      q: 0.505991
      type: Lowpass
    type: Biquad
  highpass1:
    description: null
    parameters:
      freq: 3198.21
      q: 1.22567
      type: Highpass
    type: Biquad
  highpass2:
    description: null
    parameters:
      freq: 3583.87
      q: 0.710852
      type: Highpass
    type: Biquad
  highpass3:
    description: null
    parameters:
      freq: 3935.98
      q: 0.505991
      type: Highpass
    type: Biquad
  highpass4:
    description: null
    parameters:
      freq: 3820.77
      q: 0.559609
      type: Highpass
    type: Biquad

mixers:
  stereoToLeft:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
    - dest: 0
      mute: null
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: null
        scale: null
    - dest: 1
      mute: null
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: null
        scale: null

pipeline:
- type: Mixer
  description: take left audio channel for bass and treble
  name: stereoToLeft
- type: Filter
  description: 8th order lowpass for bass speaker
  channels:
  - 0
  names:
  - lowpass1
  - lowpass2
  - lowpass3
  - lowpass4
- type: Filter
  description: 8th order highpass for treble speaker
  channels:
  - 1
  names:
  - highpass1
  - highpass2
  - highpass3
  - highpass4

