description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: hw:Loopback,1,0
    format: S32LE
    type: Alsa
  capture_samplerate: 192000
  chunksize: 2048
  enable_rate_adjust: true
  playback:
    channels: 2
    device: dmix:sndrpihifiberry
    format: S32LE
    type: Alsa
  queuelimit: null
  rate_measure_interval: null
  resampler: null
  samplerate: 192000
  silence_threshold: -60
  silence_timeout: 3
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: null
filters:
  lowpass:
    description: null
    parameters:
      type: File
      filename: /home/amp/RPi-multiroom-audio/CamillaDSP/Configuration/Coefficients/nuttall-o1001-c3500-s48000-w1.txt
      format: TEXT
    type: Conv
  highpass:
    description: null
    parameters:
      type: File
      filename: /home/amp/RPi-multiroom-audio/CamillaDSP/Configuration/Coefficients/nuttall-o1001-c3500-s48000-w2.txt
      format: TEXT
    type: Conv
mixers:
  stereoToLeft:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
    - dest: 0
      mute: null
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: null
        scale: null
    - dest: 1
      mute: null
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: null
        scale: null
pipeline:
- bypassed: null
  description: null
  name: stereoToLeft
  type: Mixer
- bypassed: null
  channels:
  - 0
  description: null
  names:
  - lowpass
  type: Filter
- bypassed: null
  channels:
  - 1
  description: null
  names:
  - highpass
  type: Filter
processors: null
title: null
